cle52up04/gromacs.cyg

Further perfected cygnet file for gromacs/4.6.7 and gromacs/5.1.1

Further perfected cygnet file for gromacs/4.6.7 and gromacs/5.1.1

---

cle52up04/gromacs.cyg

In light of ticket 16567 from Cara.

Fixed SIMD options/AVX2_256 for 5.1.1 on haswell/otherwise AVX_256

---

sles11sp4/cdo.cyg
sles11sp4/nco.cyg
sles11sp4/proj.cyg
sles11sp4/udunits.cyg

udunits is a dependency of both cdo and nco; proj is for cdo

New cygnet files for building NCO/CDO 

---

cle52up04/gromacs.cyg

Somehow the updated gromacs.cyg in the last commit isn't the one I intended for... (an elif branch is missing from the build function)

uploaded the wrong version in the last commit

---

cle52up04/abinit.cyg

Hail Ashely - The keeper of Castle Cygnet...
I have created abinit.cyg to install abinit on Intel and GNU on magnus. 
Regards
Mohsin

Added abinit.cyg to cle52up04

---

sles11sp4/cnvnator.cyg

New cygnet file for CNVnator for sles11sp4.

Created a new .cyg for CNVnator on Sles11sp4

---

sles11sp4/platanus.cyg

Created a new .cyg for Platanus for sles11sp4

Created a new .cyg for Platanus for sles11sp4

---

sles11sp4/platanus.cyg

I was downloading the source code manually last time but now have added maali_download and maali_unpack functions to do the work more smoothly.

Modified .cyg to download/unpack source code better

---

cle52up04/gromacs.cyg

Added version 5.0.5 as an option so people can install it in their group directory.

Added 5.0.5 as an option

---

sles11sp4/braker.cyg
sles11sp4/genemark-et.cyg

Created cygnet files for GeneMark-ET suite and BRAKER on Sles11sp4.

Genemark braker

---

cle52up04/emcee.cyg
cle52up04/memory_profiler.cyg

Basically it trying to install in base python
Replace it with the generic base python build function

memory_profiler.cyg update

---

sles11sp4/cuda.cyg

Preliminary Support for Cuda 8 and cudnn 6

Modified cuda.cyg

---

cle52up04/openfoam-esi.cyg

Updated to add modifications required to build v1612+ on Magnus

OpenFOAM+ maali file openfoam-esi.cyg updated

---

cle52up04/openfoam-esi.cyg

Fix an error in maali_download{ }

amended openfoam-esi.cyg

---

sles12sp2/armadillo.cyg
sles12sp2/mvapich.cyg

Removed sed lines and added KNL flags for both GNU and Intel compilers.

Modified cygnet files for SLES12SP2/Athena

---

cle52up04/bison.cyg
cle52up04/flex.cyg

The previous URL was a mirror which doesn't exist anymore

Amended the MAALI_URL. 

---

sles12sp2/cuda.cyg

CPU targets included in cyg file.  Supports Intel too.

Cuda works with GCC6, supports cudnn.

---

sles12sp2/cuda.cyg

PGI/17 now supported
Only builds samples for system builds
cuDNN 7 for CUDA 7/8 supported

Quite a few changes for cuda.cyg

---

sles12sp2/openmpi.cyg

modified OpenMPI cygnet file to allow OpenMPI support on Athena with multiple CUDA gpus.

modified OpenMPI cygnet file to include CUDA support

---

singularity.cyg

added singularity cygnet file

---

cle52up04/pint.cyg
cle52up04/setuptools.cyg

… added support for the Pint Python module.
Setuptools updated to use releases from GitHUB.

Mcheeseman cle42up04 pint

---

sles12sp2/stream.cyg

A component of performance benchmark toolset on Pawsey resources.

STREAM benchmark

---

sles12sp2/cffi.cyg
sles12sp2/magma.cyg
sles12sp2/pytorch.cyg

PyTorch, Magma and CFFI support added

added PyTorch and its missing dependencies

---

sles12sp2/functools32.cyg
sles12sp2/matplotlib.cyg
sles12sp2/scikit-learn.cyg

Added new cygfile for SCiKit_learning python package support.  Had to modify the cygfiles for Matplotlib and functools32 to get the package built

added SciKit-Learn and its missing dependencies

---

sles12sp2/r.cyg

MAALI_URL needed to be updated for R to allow installation of versions above 3.4.0.  Intel compiler support added as well

Mcheeseman sles12sp2 r

---

cle52up04/rmextract.cyg

Added new cygnet file to add support for RMextract python module

added RMextract python module support

---

sles12sp3/openfoam.cyg
sles12sp3/qt.cyg

NOTE: This only works for QT5 and up

Modified QT and OpenFOAM to support Intel compilers

---

sles12sp2/keras.cyg
sles12sp2/libgpuarray.cyg
sles12sp2/theano.cyg

LibGPUarray and Theano are new cygnet files.  Have updated Keras cygnet file so that it doesn't depend on specific versions of various Python packages.

added libgpuarray and theano support

---

cle60up05/imfit.cyg
cle60up05/nlopt.cyg

added support for imfit and NLopt packages.  Requested by MWA people

added imfit and nlopt cygnet files

---

cle60up05/gromacs.cyg

https://redmine.gromacs.org/issues/2414

correcting a bug in gromacs/2018 - simulations failing with -multidir

---

sles12sp3/cfitsio.cyg

* add support to do shared libraries for cfitsio for sles12sp3

Modify cfitsio for sles12sp3

---

cle60up05/lapack.cyg
sles12sp3/lapack.cyg

just removed some debugging echo commands

Marco: minimal fix to lapack cyg 2x

---

sles12sp3/cuda.cyg

Update cuda to support updated version of cudnn

---

sles12sp3/singularity.cyg

Singularity for sles12sp3 (Version 2/3 support)

---

sles12sp3/ansys.cyg

This reverts commit 6507ac3ec2bd1ce4f96c178f150bc3b2b731522c.

Revert previous commit, disable KMP_AFFINITY.

---

sles12sp3/singularity.cyg

Support for last Stable update 3.2.1 looks like something changed in Google Go version

Singularity Update

---

cle60up05/reframe.cyg
sles12sp3/reframe.cyg

It should work for version < 2.18

ReFrame installation recipe for Pawsey systems

---

sles12sp3/dualsphysics.cyg

cygnet file prepared for Prof. Ryan Lowe (Oceans Institute UWA)
Ticket: GS-12249

DualSPHysics cygnet file

---

sles12sp3/doxygen.cyg

package to build docs
now 
- using system_gcc
- not building variants for CPU archs

Doxygen - updated for sles12sp3

---

centos7.6/singularity.cyg

Singularity for centos7.6 / Topaz

---

cle60up07/siesta.cyg

Adds the cygnet file for Siesta. It had to be updated since the project is moving to gitlab and building instruction changed a little bit.

Adds cygnet file for Siesta software.

---

centos7.6/vmd.cyg

Additional features:
- Support for IMD i.e. Interactive Molecular Dynamics
- CUDA support (certain analyses, Zeus only as VMD 1.9.3 does not compile with CUDA 10)
- MPI support (certain analyses, no visualisation, only via TCL scripts)

VMD with extra features for sles and centos

---

mwa_sles12sp4/pawseytools.cyg
mwa_sles12sp4/python.cyg

Simply adds python and pawseytools cygnet files for some initial work.

adds initial support for mwa cluster on sles12sp4

---

topaz_centos7.6/magma.cyg

Just adding magma cygnet file. Should magma be installed system-wide?

Adds magma cygnet file.

---

topaz_centos7.6/vasp.cyg

Adds vasp with gpu support. Note that the path to the source code is hard coded, maybe we can use an env variable.

Adds vasp.cyg

---

centos7.6/fftw.cyg

Just copied the one for ubuntu with minor updates.

Adds fftw cygnet file

---

centos7.6/magma.cyg

Added broadwell so pascal nodes can be merged into topaz

Magma - added broadwell, tidied up

---

centos7.6/opencv.cyg

Ml for topaz

---

mwa_sles12sp4/singularity.cyg

This looks to be working from our tests

adds mpi paths and correct cachedir

---

cle60up07/h5py.cyg

update to cygnet to handle compiling mpi h5py.

Update to h5py cygnet to handle building mpi version

---

generic/rclone.cyg
sles12sp3/rclone.cyg

This is a cyg file that will create the rclone 1.55.0 version module for sles12sp3.

Rclone cygfile generic

---

centos7.6/gromacs.cyg

Rewritten most of it.
- Cleanup
- Added support for VMD plugin
- Added cuda support.

Updates gromacs cygnet file for topaz

---

centos7.6/ninja.cyg
sles12sp3/ninja.cyg

Ninja build tool
* Needed to build other tools / libraries
* Needed for jwt support ie slurm

Akmchew patch 5

---

centos7.6/boost.cyg

Specifies the python development library needed to build python bindings

Updates boost.cyg

---

centos7.6/gromacs.cyg
centos7.6/plumed2.cyg

gromacs
- Adds code (commented out) to patch with plumed
- Simplify cygnet file, removes double precision build which is not supported with gpu
- Fixes incorrect build options
plumed2, simply added cygnet file

Updates gromacs cygnet and adds plumed2
