PawseySC/maali-cygnet

sles11sp4/oommf.cyg

Added a file for future refer for installing a TCL script based installation of oommf. This cygnet file is for Zeus only.

Adding oommf.cyg for Zeus installation

---

cle52up04/casacore.cyg

Hi, 
I have updated casacore.cyg so that it can download Versions 2.0 and greater from github repo. 
The rest of the script is the same. 
Regards
Mohsin.

Amended casacore.cyg to add URL for Versions 2.0 and onwards

---

cle52up04/armadillo.cyg
cle52up04/tvc.cyg

- created cygnet file for Ion Torrent Variant Caller on cle52up04
- fixed armadillo.cyg as one of TVC's dependencies

working cygnet file for TVC-5.0.0 on cle52up04

---

cle52up04/gromacs.cyg

-- In light of Issue17796, this merge fixes bug #1848 as detailed in http://redmine.gromacs.org/issues/1848. 
-- Version 5.0.5 and 5.1.2 are fine.

Fixed bug #1848 in Gromacs/5.1.1

---

cle52up04/healpy.cyg
cle52up04/memory_profiler.cyg

* Used maali python generic build function to address installation to base python which it should not
* Add missing dependency cython, matplotlib, astropy else it attempts the python easy install.

healpy.cyg PAtch

---

cle52up04/netcdf4-python.cyg
sles11sp4/cairo.cyg
sles11sp4/ncl.cyg
sles11sp4/pixman.cyg

new cygnet file for netcdf4-python on cle52;
copied pixman and cairo cygnet files on cle52 to sles11;
new cygnet file for NCAR command language on sles11.

cygnet files for netcdf4-python, pixman, cairo, and NCL

---

cle52up04/cgal.cyg
cle52up04/jive5ab.cyg
cle52up04/openfoam-esi.cyg

Adding OpenFOAM build recipe for ESI's OpenFOAM+ versions. 
Tested with v1606+.
Requires cgal/4.8.x 
Added cgal.cyg for completeness

Adding OpenFOAM build recipe for ESI's OpenFOAM+ versions. 

---

sles12sp2/fftw.cyg
sles12sp2/gsl.cyg

Modified FFTW cygfile to distinguish between a FFTW-3 and FFTW-2 build.  KNL support added for both an Intel and GNU build.
Modified GSL cygfile to add KNL support.  Both Intel and GNU builds are defined

Mcheeseman knl fftw gsl

---

sles12sp2/bazel.cyg

Bazel is the build tool for TensorFlow.  The added configuration enables CUDA, GCC 5.4.0 and Intel MKL build support for x86_64 architectures.

added Bazel cygnet file

---

cle52up04/jasper.cyg

Jasper added .  It is a dependency for WRF.  Versions 2.0.+ require a CMake build now. (oh yay)

add Jasper support (both CMake and autotools versions)

---

cle60up05/bison.cyg
cle60up05/flex.cyg

The systems versions are older than required by MWA.

adding flex AND bison cygnets to repo.

---

cle60up05/mpi4py.cyg

Added changes so that mpi4py will be built on the crays.  Previous cygnet file was more geared towards the generic x86 cluster platform.

removed broadwell/1.0 module req. Added missing PrgEnv definition

---

cle60up05/boost.cyg

Will build boost/1.64.0 with both gcc and intel compilers on CLE6.

Adding boost tested with version 1.64.0 with python support

---

sles12sp3/openfoam+.cyg
sles12sp3/openfoam.cyg

Intel compiler support added
ParaView build fixed
Collated file IO added to module
This still needs a maali fix to deal with the quotes and os.genv
conversion.  As it stands, this will compile openfoam and openfoam+
but it will require hand-modification of the generated modulefile

Added updated OpenFOAM cygnet files

---

cle60up05/gerris.cyg
cle60up05/gts.cyg

Removed reference to glib module. Sytem glib can now be used for GTS and Gerris builds.

removed reference to nonexistant glib module

---

cle60up05/cpmd.cyg

added new cygnet file that supports the Intel and Cray compiler builds of CPMD Version 4.1

add support for CPMD v4.1

---

cle60up05/pawseytools.cyg

Adding munlink to shared tools area. This does require a compile of munlink.c but it doesn't have any prereqs apart from system include files and is only 32 lines of source.

Adding munlink to cygnetfile for Pawseytools

---

sles12sp3/hdf5-parallel.cyg

HDF5 with parallel I/O support enabled via OpenMPI for both GNU and Intel compilers.  Needed as part of the Casacore install

added parallel HDF5 support

---

sles12sp3/boost.cyg
sles12sp3/hdf5-parallel.cyg

Support for Version 1.66.0 added which uses new b2 install tool.  Support for Python libraries in Boost also enabled.

added support for latest version and python libraries in Boost

---

sles12sp3/casacore.cyg

Added support for Casacore. Tested the latest version (2.4.1) using parallel HDF5 and rebuilt Boost 1.66.0 with Python library support enabled.

added casacore

---

sles12sp3/casacore.cyg

Removed gcc/4.8.5 support in casacore as the boost library required does not have support for that compiler version.

removed gcc/4.8.5 support for casacore

---

sles12sp3/soap3.cyg

updated sles12sp3/soap3.cyg to fix libcuda.so not found when building

Marco - updated sles12sp3/soap3.cyg

---

sles12sp3/soap3-dp.cyg
sles12sp3/soap3.cyg

soap3-dp : new cyg file for Zeus (only gcc4 and gcc5)
soap3 : added patch for bug in source code
for both, compiler names and flags had to be set in cyg file, as developer uses c++ standards in c source files

Marco: added soap3-dp cyg for Zeus ; added patch for soap3 source

---

cle60up05/lammps.cyg

1- made MAALI_URL and MAALI_DST able to deal with different versions (not only the latest)
2- disabled compilation of package mscg : there is a compile time error likely caused by bugs in the code ; I am not investigating it until users need it
3- disabled compilation of new package latte : requires additional build instructions, not investigating it until users need it

Marco: mods to cle60up05/lammps.cyg to build recent versions

---

sles12sp3/cuffs.cyg
sles12sp3/libconfig.cyg

cuFFS support added due to an user support request.  lidconfig.cyg was updated to work with the latest version (1.7.2)

libconfig now installs properly. cuFFS support added

---

sles12sp3/keras.cyg

Existing KERAS module on Zeus has syntax issue when an user tries to load the module.  Have added HDF5 support so that restart files for weight values can now be written.

Fixed module syntax.  Added HDF5 support for restart file generation.

---

cle60up05/bzr.cyg

Paramiko and PyCrypto are not installed on Magnus and do not have working Maali cygnet files.  However, Bazaar works fine without them.

removed paramiko and pycrypto dependencies on bazaar install

---

sles12sp3/rmblast.cyg

This follows discussion in CR-1230 (https://support.pawsey.org.au/portal/browse/CR-1230), 
to reduce the number of BOOST versions on Zeus.
This was the only dependency on boost/1.62.0.
The updated build recipe reflects the installation instructions for RMBLAST as found on its website:
http://www.repeatmasker.org/RMBlast.html

sles12sp3/rmblast : removed dependency from boost lib

---

sles12sp3/cuda.cyg

Cuda 10.x Patch
* There is no offical support for sles12 for cuda 10.0
* There is only support for sles12sp4 for cuda 10.1 (Looks binary compatible for sles12sp3)
* Cuda 10.1 requires nvidia module 418.67+

Cuda 10.1 Patch for sles12sp3

---

centos7.6/singularity.cyg

Add support for broken version 3.5.1|3.5.0
* Needs a custom patch
* Basically requires google go version 1.13.x but fails internally
* Patch allows previous version of google go

Update Singularity for Centos 7.6

---

cle60up07/singularity.cyg

singularity.cyg: LD_LIBRARY_PATH updated, because MPI failed on Magnus after July maintainance

singularity.cyg: LD_LIBRARY_PATH updated

---

centos7.6/r.cyg

Add the Maali Cygnet file used for installing R on Topaz.

Adding the cygnet file for installing R on Topaz

---

cle60up07/qe.cyg

Update to quantum expresso cygnet to handle changes present in 6.6

Update quantum expresso cygnet to work with >=6.6

---

centos7.6/singularity-openmpi.cyg
centos7.6/singularity.cyg
mwa_sles12sp4/singularity-openmpi.cyg
mwa_sles12sp4/singularity.cyg
sles12sp3/singularity-openmpi.cyg

Topaz and Garrawarla:
- added MPICH support
- new singularity-openmpi module with OpenMPI support
Zeus:
- new singularity-openmpi module with OpenMPI support
Tested for CPU applications only right now

Singularity for MPI updated for all clusters

---

centos7.6/hip.cyg

Added a cygnet file for the rocm-3.8.0 release of HIP on Topaz using the CUDA backend.
Tested a local maali install on the V100 and P100 nodes.

Added cygnet for HIP with CUDA backend on Topaz
